package main

import (
	"fmt"
	"log"
)

// Product represents a product with various numeric validations
type Product struct {
	ID          int     `validate:"gt=0"`              // ID must be greater than 0
	Price       float64 `validate:"gte=0.01"`          // Price must be at least 0.01
	Quantity    int     `validate:"gte=1"`             // Quantity must be at least 1
	Rating      float64 `validate:"gte=0,lte=5"`       // Rating must be between 0 and 5
	Description string  `validate:"required,gt=10"`    // Description must be longer than 10 characters
	Tags        []string `validate:"required,gte=1"`   // At least one tag is required
}

// Validate validates the Product struct
func (p *Product) Validate() error {
	// This function will be generated by quickvalidate
	return nil
}

func main() {
	// Create an invalid product
	invalidProduct := &Product{
		ID:          0,           // Invalid: ID must be greater than 0
		Price:       0,           // Invalid: Price must be at least 0.01
		Quantity:    0,           // Invalid: Quantity must be at least 1
		Rating:      6,           // Invalid: Rating must be between 0 and 5
		Description: "Short",     // Invalid: Description must be longer than 10 characters
		Tags:        []string{},  // Invalid: At least one tag is required
	}

	// Validate the invalid product
	err := invalidProduct.Validate()
	if err != nil {
		log.Printf("Validation errors: %v\n", err)
	} else {
		log.Println("Invalid product passed validation - this is unexpected!")
	}

	// Create a valid product
	validProduct := &Product{
		ID:          1,
		Price:       9.99,
		Quantity:    10,
		Rating:      4.5,
		Description: "This is a valid product description",
		Tags:        []string{"electronics", "gadget"},
	}

	// Validate the valid product
	err = validProduct.Validate()
	if err != nil {
		log.Printf("Unexpected validation errors: %v\n", err)
	} else {
		log.Println("Valid product passed validation successfully!")
	}

	fmt.Println("Done!")
}
