// Code generated by quickvalidate. DO NOT EDIT.

package main

import (
	"github.com/antlabs/quickvalidate/pkg/errors"
	"reflect"
)

// Validate validates the Product struct.
func (s *Product) Validate() error {
	return s.validate("Product")
}

// validate validates the Product struct, building namespaces with nsPrefix.
func (s *Product) validate(nsPrefix string) error {
	var errs errors.ValidationErrors
	if !(int64(s.ID) > 0) {
		errs = append(errs, errors.ValidationError{
			Field:           "ID",
			Tag:             "gt",
			Param:           "0",
			Namespace:       nsPrefix + ".ID",
			StructNamespace: nsPrefix + ".ID",
			ActualTag:       "gt",
			Kind:            reflect.Int,
			Value:           s.ID,
		})
	}
	if !(s.Price >= 0.01) {
		errs = append(errs, errors.ValidationError{
			Field:           "Price",
			Tag:             "gte",
			Param:           "0.01",
			Namespace:       nsPrefix + ".Price",
			StructNamespace: nsPrefix + ".Price",
			ActualTag:       "gte",
			Kind:            reflect.Float64,
			Value:           s.Price,
		})
	}
	if !(int64(s.Stock) >= 0) {
		errs = append(errs, errors.ValidationError{
			Field:           "Stock",
			Tag:             "gte",
			Param:           "0",
			Namespace:       nsPrefix + ".Stock",
			StructNamespace: nsPrefix + ".Stock",
			ActualTag:       "gte",
			Kind:            reflect.Int,
			Value:           s.Stock,
		})
	}
	if !(s.Weight > 0) {
		errs = append(errs, errors.ValidationError{
			Field:           "Weight",
			Tag:             "gt",
			Param:           "0",
			Namespace:       nsPrefix + ".Weight",
			StructNamespace: nsPrefix + ".Weight",
			ActualTag:       "gt",
			Kind:            reflect.Float64,
			Value:           s.Weight,
		})
	} else {
		if !(s.Weight < 1000) {
			errs = append(errs, errors.ValidationError{
				Field:           "Weight",
				Tag:             "lt",
				Param:           "1000",
				Namespace:       nsPrefix + ".Weight",
				StructNamespace: nsPrefix + ".Weight",
				ActualTag:       "lt",
				Kind:            reflect.Float64,
				Value:           s.Weight,
			})
		}
	}
	if !(s.Rating >= 0) {
		errs = append(errs, errors.ValidationError{
			Field:           "Rating",
			Tag:             "gte",
			Param:           "0",
			Namespace:       nsPrefix + ".Rating",
			StructNamespace: nsPrefix + ".Rating",
			ActualTag:       "gte",
			Kind:            reflect.Float64,
			Value:           s.Rating,
		})
	} else {
		if !(s.Rating <= 5) {
			errs = append(errs, errors.ValidationError{
				Field:           "Rating",
				Tag:             "lte",
				Param:           "5",
				Namespace:       nsPrefix + ".Rating",
				StructNamespace: nsPrefix + ".Rating",
				ActualTag:       "lte",
				Kind:            reflect.Float64,
				Value:           s.Rating,
			})
		}
	}
	if !(int64(s.CategoryID) == 1) {
		errs = append(errs, errors.ValidationError{
			Field:           "CategoryID",
			Tag:             "eq",
			Param:           "1",
			Namespace:       nsPrefix + ".CategoryID",
			StructNamespace: nsPrefix + ".CategoryID",
			ActualTag:       "eq",
			Kind:            reflect.Int,
			Value:           s.CategoryID,
		})
	}
	if !(int64(s.MaxQuantity) == 10) {
		errs = append(errs, errors.ValidationError{
			Field:           "MaxQuantity",
			Tag:             "eq",
			Param:           "10",
			Namespace:       nsPrefix + ".MaxQuantity",
			StructNamespace: nsPrefix + ".MaxQuantity",
			ActualTag:       "eq",
			Kind:            reflect.Int,
			Value:           s.MaxQuantity,
		})
	}
	if !(int64(s.MinAge) <= 18) {
		errs = append(errs, errors.ValidationError{
			Field:           "MinAge",
			Tag:             "lte",
			Param:           "18",
			Namespace:       nsPrefix + ".MinAge",
			StructNamespace: nsPrefix + ".MinAge",
			ActualTag:       "lte",
			Kind:            reflect.Int,
			Value:           s.MinAge,
		})
	}
	if !(int64(s.MaxAge) >= 18) {
		errs = append(errs, errors.ValidationError{
			Field:           "MaxAge",
			Tag:             "gte",
			Param:           "18",
			Namespace:       nsPrefix + ".MaxAge",
			StructNamespace: nsPrefix + ".MaxAge",
			ActualTag:       "gte",
			Kind:            reflect.Int,
			Value:           s.MaxAge,
		})
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}

// Validate validates the Order struct.
func (s *Order) Validate() error {
	return s.validate("Order")
}

// validate validates the Order struct, building namespaces with nsPrefix.
func (s *Order) validate(nsPrefix string) error {
	var errs errors.ValidationErrors
	if !(int64(s.OrderID) > 1000) {
		errs = append(errs, errors.ValidationError{
			Field:           "OrderID",
			Tag:             "gt",
			Param:           "1000",
			Namespace:       nsPrefix + ".OrderID",
			StructNamespace: nsPrefix + ".OrderID",
			ActualTag:       "gt",
			Kind:            reflect.Int,
			Value:           s.OrderID,
		})
	}
	if !(s.TotalAmount > 0) {
		errs = append(errs, errors.ValidationError{
			Field:           "TotalAmount",
			Tag:             "gt",
			Param:           "0",
			Namespace:       nsPrefix + ".TotalAmount",
			StructNamespace: nsPrefix + ".TotalAmount",
			ActualTag:       "gt",
			Kind:            reflect.Float64,
			Value:           s.TotalAmount,
		})
	}
	if !(int64(s.ItemCount) > 0) {
		errs = append(errs, errors.ValidationError{
			Field:           "ItemCount",
			Tag:             "gt",
			Param:           "0",
			Namespace:       nsPrefix + ".ItemCount",
			StructNamespace: nsPrefix + ".ItemCount",
			ActualTag:       "gt",
			Kind:            reflect.Int,
			Value:           s.ItemCount,
		})
	} else {
		if !(int64(s.ItemCount) <= 100) {
			errs = append(errs, errors.ValidationError{
				Field:           "ItemCount",
				Tag:             "lte",
				Param:           "100",
				Namespace:       nsPrefix + ".ItemCount",
				StructNamespace: nsPrefix + ".ItemCount",
				ActualTag:       "lte",
				Kind:            reflect.Int,
				Value:           s.ItemCount,
			})
		}
	}
	if !(s.Status == "pending") {
		errs = append(errs, errors.ValidationError{
			Field:           "Status",
			Tag:             "eq",
			Param:           "pending",
			Namespace:       nsPrefix + ".Status",
			StructNamespace: nsPrefix + ".Status",
			ActualTag:       "eq",
			Kind:            reflect.String,
			Value:           s.Status,
		})
	}
	if !(int64(s.Priority) == 1) {
		errs = append(errs, errors.ValidationError{
			Field:           "Priority",
			Tag:             "eq",
			Param:           "1",
			Namespace:       nsPrefix + ".Priority",
			StructNamespace: nsPrefix + ".Priority",
			ActualTag:       "eq",
			Kind:            reflect.Int,
			Value:           s.Priority,
		})
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}
