// Code generated by quickvalidate. DO NOT EDIT.

package main

import (
	"github.com/antlabs/quickvalidate/pkg/errors"
	qv "github.com/antlabs/quickvalidate/pkg/validators"
	"reflect"
	"strconv"
)

var qvHelper1 = []string{"male", "female", "prefer_not_to"}

// Validate validates the User struct.
func (s *User) Validate() error {
	return s.validate("User")
}

// validate validates the User struct, building namespaces with nsPrefix.
func (s *User) validate(nsPrefix string) error {
	var errs errors.ValidationErrors
	if !(s.FirstName != "") {
		errs = append(errs, errors.ValidationError{
			Field:           "FirstName",
			Tag:             "required",
			Namespace:       nsPrefix + ".FirstName",
			StructNamespace: nsPrefix + ".FirstName",
			ActualTag:       "required",
			Kind:            reflect.String,
			Value:           s.FirstName,
		})
	}
	if !(s.LastName != "") {
		errs = append(errs, errors.ValidationError{
			Field:           "LastName",
			Tag:             "required",
			Namespace:       nsPrefix + ".LastName",
			StructNamespace: nsPrefix + ".LastName",
			ActualTag:       "required",
			Kind:            reflect.String,
			Value:           s.LastName,
		})
	}
	if !(uint64(s.Age) >= 0) {
		errs = append(errs, errors.ValidationError{
			Field:           "Age",
			Tag:             "gte",
			Param:           "0",
			Namespace:       nsPrefix + ".Age",
			StructNamespace: nsPrefix + ".Age",
			ActualTag:       "gte",
			Kind:            reflect.Uint8,
			Value:           s.Age,
		})
	} else {
		if !(uint64(s.Age) <= 130) {
			errs = append(errs, errors.ValidationError{
				Field:           "Age",
				Tag:             "lte",
				Param:           "130",
				Namespace:       nsPrefix + ".Age",
				StructNamespace: nsPrefix + ".Age",
				ActualTag:       "lte",
				Kind:            reflect.Uint8,
				Value:           s.Age,
			})
		}
	}
	if !(s.Email != "") {
		errs = append(errs, errors.ValidationError{
			Field:           "Email",
			Tag:             "required",
			Namespace:       nsPrefix + ".Email",
			StructNamespace: nsPrefix + ".Email",
			ActualTag:       "required",
			Kind:            reflect.String,
			Value:           s.Email,
		})
	} else {
		if !(qv.IsEmail(s.Email)) {
			errs = append(errs, errors.ValidationError{
				Field:           "Email",
				Tag:             "email",
				Namespace:       nsPrefix + ".Email",
				StructNamespace: nsPrefix + ".Email",
				ActualTag:       "email",
				Kind:            reflect.String,
				Value:           s.Email,
			})
		}
	}
	if !(qv.IsOneOf(s.Gender, qvHelper1)) {
		errs = append(errs, errors.ValidationError{
			Field:           "Gender",
			Tag:             "oneof",
			Param:           "male female prefer_not_to",
			Namespace:       nsPrefix + ".Gender",
			StructNamespace: nsPrefix + ".Gender",
			ActualTag:       "oneof",
			Kind:            reflect.String,
			Value:           s.Gender,
		})
	}
	if !((qv.IsHEXColor(s.FavouriteColor)) || (qv.IsRGB(s.FavouriteColor)) || (qv.IsRGBA(s.FavouriteColor)) || (qv.IsHSL(s.FavouriteColor)) || (qv.IsHSLA(s.FavouriteColor))) {
		errs = append(errs, errors.ValidationError{
			Field:           "FavouriteColor",
			Tag:             "iscolor",
			Namespace:       nsPrefix + ".FavouriteColor",
			StructNamespace: nsPrefix + ".FavouriteColor",
			ActualTag:       "hexcolor|rgb|rgba|hsl|hsla",
			Kind:            reflect.String,
			Value:           s.FavouriteColor,
		})
	}
	if !(qv.IsURL(s.Website)) {
		errs = append(errs, errors.ValidationError{
			Field:           "Website",
			Tag:             "url",
			Namespace:       nsPrefix + ".Website",
			StructNamespace: nsPrefix + ".Website",
			ActualTag:       "url",
			Kind:            reflect.String,
			Value:           s.Website,
		})
	}
	if !(s.Addresses != nil) {
		errs = append(errs, errors.ValidationError{
			Field:           "Addresses",
			Tag:             "required",
			Namespace:       nsPrefix + ".Addresses",
			StructNamespace: nsPrefix + ".Addresses",
			ActualTag:       "required",
			Kind:            reflect.Slice,
			Value:           s.Addresses,
		})
	} else {
		for i1 := range s.Addresses {
			{
				if s.Addresses[i1] != nil {
					if !(true) {
						errs = append(errs, errors.ValidationError{
							Field:           "Addresses" + "[" + strconv.Itoa(i1) + "]",
							Tag:             "required",
							Namespace:       nsPrefix + ".Addresses" + "[" + strconv.Itoa(i1) + "]",
							StructNamespace: nsPrefix + ".Addresses" + "[" + strconv.Itoa(i1) + "]",
							ActualTag:       "required",
							Kind:            reflect.Struct,
							Value:           (*s.Addresses[i1]),
						})
					} else {
						if err := (*s.Addresses[i1]).validate(nsPrefix + ".Addresses" + "[" + strconv.Itoa(i1) + "]"); err != nil {
							if verrs, ok := err.(errors.ValidationErrors); ok {
								errs = append(errs, verrs...)
							} else if err != nil {
								return err
							}
						}
					}
				} else {
					errs = append(errs, errors.ValidationError{
						Field:           "Addresses" + "[" + strconv.Itoa(i1) + "]",
						Tag:             "required",
						Namespace:       nsPrefix + ".Addresses" + "[" + strconv.Itoa(i1) + "]",
						StructNamespace: nsPrefix + ".Addresses" + "[" + strconv.Itoa(i1) + "]",
						ActualTag:       "required",
						Kind:            reflect.Ptr,
						Value:           s.Addresses[i1],
					})
				}
			}
		}
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}

// Validate validates the Address struct.
func (s *Address) Validate() error {
	return s.validate("Address")
}

// validate validates the Address struct, building namespaces with nsPrefix.
func (s *Address) validate(nsPrefix string) error {
	var errs errors.ValidationErrors
	if !(s.Street != "") {
		errs = append(errs, errors.ValidationError{
			Field:           "Street",
			Tag:             "required",
			Namespace:       nsPrefix + ".Street",
			StructNamespace: nsPrefix + ".Street",
			ActualTag:       "required",
			Kind:            reflect.String,
			Value:           s.Street,
		})
	}
	if !(s.City != "") {
		errs = append(errs, errors.ValidationError{
			Field:           "City",
			Tag:             "required",
			Namespace:       nsPrefix + ".City",
			StructNamespace: nsPrefix + ".City",
			ActualTag:       "required",
			Kind:            reflect.String,
			Value:           s.City,
		})
	}
	if !(s.Planet != "") {
		errs = append(errs, errors.ValidationError{
			Field:           "Planet",
			Tag:             "required",
			Namespace:       nsPrefix + ".Planet",
			StructNamespace: nsPrefix + ".Planet",
			ActualTag:       "required",
			Kind:            reflect.String,
			Value:           s.Planet,
		})
	}
	if !(s.Phone != "") {
		errs = append(errs, errors.ValidationError{
			Field:           "Phone",
			Tag:             "required",
			Namespace:       nsPrefix + ".Phone",
			StructNamespace: nsPrefix + ".Phone",
			ActualTag:       "required",
			Kind:            reflect.String,
			Value:           s.Phone,
		})
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}
