package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/antlabs/quickvalidate/pkg/parser"
)

// Generator emits static validation code for a parsed package.
type Generator struct {
	Pkg *parser.Package

	imports  map[string]string // import path -> alias ("" when the package name is used)
	vars     []string          // package level var declarations, deduplicated by key
	varByKey map[string]string
}

// NewGenerator creates a Generator for pkg.
func NewGenerator(pkg *parser.Package) *Generator {
	parser.KnownTags = knownTags()
	return &Generator{
		Pkg:      pkg,
		imports:  map[string]string{},
		varByKey: map[string]string{},
	}
}

// fieldRef is a value being validated: a struct field or an element reached
// through dive.
type fieldRef struct {
	// expr is the Go expression evaluating to the value, e.g. "s.Email".
	expr string
	typ  *parser.TypeInfo
	// name is the static field name, e.g. "Email".
	name string
	// fieldExpr is a Go string expression producing the field name, e.g.
	// `"Items" + "[" + strconv.Itoa(i1) + "]"`.
	fieldExpr string
	// ns is a Go expression evaluating to the namespace prefix *without* the
	// field name, e.g. `nsPrefix + ".User"`.
	ns string
	// parent is the Go expression of the enclosing struct, used by cross-field tags.
	parent string
	// ptr marks refs whose value is known to be nil (inside a nil branch).
	knownNil bool
	// fromPointer marks refs reached by dereferencing a pointer: validator's
	// hasValue reports true for any non-nil pointer, whatever it points at.
	fromPointer bool
}

// arg renders the field as an argument of its underlying predeclared type.
//
// validator reads fields through reflection, so `type Email string` behaves as
// a string, but Go does not convert implicitly: passing an Email to a helper
// that takes a string does not compile. Named types therefore go through an
// explicit conversion, which is only done where a value is handed to a typed
// function — comparisons against untyped constants, len(), and method calls all
// work on the named type as it is.
func (ref fieldRef) arg() string { return convert(ref.expr, ref.typ) }

// convert is arg for an expression and type that do not come from a fieldRef,
// such as the other side of a cross field comparison.
func convert(expr string, typ *parser.TypeInfo) string {
	builtin := typ.BuiltinName()
	if typ == nil || !typ.Named || builtin == "" {
		return expr
	}
	return builtin + "(" + expr + ")"
}

// cmpOperands renders both sides of a cross field comparison in their common
// underlying type. A named type has to be converted explicitly, and when one
// side is converted the other must be too, so that both end up in one type.
func cmpOperands(a string, at *parser.TypeInfo, b string, bt *parser.TypeInfo) (string, string) {
	if !at.Named && !bt.Named {
		return a, b
	}
	builtin := at.BuiltinName()
	return builtin + "(" + a + ")", builtin + "(" + b + ")"
}

type structEmitter struct {
	g    *Generator
	name string
	w    *codeWriter
	// fields indexes the current struct's fields by name for cross field tags.
	fields map[string]*parser.FieldInfo
	// diveDepth numbers the loop variables of nested dives so they never shadow
	// each other.
	diveDepth int
}

// Generate renders the whole package.
func (g *Generator) Generate() ([]byte, error) {
	var body bytes.Buffer
	for _, s := range g.Pkg.Structs {
		se := &structEmitter{g: g, name: s.Name, w: newWriter(&body), fields: map[string]*parser.FieldInfo{}}
		for i := range s.Fields {
			se.fields[s.Fields[i].Name] = &s.Fields[i]
		}
		if err := se.emit(s); err != nil {
			return nil, fmt.Errorf("struct %s: %w", s.Name, err)
		}
		body.WriteString("\n")
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by quickvalidate. DO NOT EDIT.\n\npackage %s\n\n", g.Pkg.Name)
	if len(g.imports) > 0 {
		out.WriteString("import (\n")
		paths := make([]string, 0, len(g.imports))
		for p := range g.imports {
			paths = append(paths, p)
		}
		sort.Strings(paths)
		for _, p := range paths {
			if alias := g.imports[p]; alias != "" {
				fmt.Fprintf(&out, "\t%s %q\n", alias, p)
			} else {
				fmt.Fprintf(&out, "\t%q\n", p)
			}
		}
		out.WriteString(")\n\n")
	}
	for _, v := range g.vars {
		out.WriteString(v)
		out.WriteString("\n")
	}
	if len(g.vars) > 0 {
		out.WriteString("\n")
	}
	out.Write(body.Bytes())

	src, err := format.Source(out.Bytes())
	if err != nil {
		return out.Bytes(), fmt.Errorf("format generated code: %w", err)
	}
	return src, nil
}

// addImport records an import and returns the selector to use.
func (g *Generator) addImport(path, alias string) string {
	g.imports[path] = alias
	if alias != "" {
		return alias
	}
	base := path
	if i := strings.LastIndex(base, "/"); i >= 0 {
		base = base[i+1:]
	}
	return base
}

// errPkg imports the ValidationError package and returns its selector.
func (g *Generator) errPkg() string {
	return g.addImport("github.com/antlabs/quickvalidate/pkg/errors", "")
}

// helperVar declares a package level variable once, keyed by key.
func (g *Generator) helperVar(key, decl string) string {
	if name, ok := g.varByKey[key]; ok {
		return name
	}
	name := fmt.Sprintf("qvHelper%d", len(g.vars)+1)
	g.varByKey[key] = name
	g.vars = append(g.vars, "var "+name+" = "+decl)
	return name
}

func (se *structEmitter) emit(s *parser.StructInfo) error {
	g := se.g
	errsPkg := g.errPkg()

	se.w.printf("// Validate validates the %s struct.\n", s.Name)
	se.w.printf("func (s *%s) Validate() error {\n", s.Name)
	se.w.printf("\treturn s.validate(\"%s\")\n", s.Name)
	se.w.printf("}\n\n")

	se.w.printf("// validate validates the %s struct, building namespaces with nsPrefix.\n", s.Name)
	se.w.printf("func (s *%s) validate(nsPrefix string) error {\n", s.Name)
	se.w.indent(1)
	se.w.printf("var errs %s.ValidationErrors\n", errsPkg)

	for i := range s.Fields {
		f := &s.Fields[i]
		ref := fieldRef{
			expr:      "s." + f.Name,
			typ:       f.Type,
			name:      f.Name,
			fieldExpr: fmt.Sprintf("%q", f.Name),
			ns:        fmt.Sprintf("nsPrefix + %q", "."+f.Name),
			parent:    "s",
		}
		if err := se.emitField(ref, f.Tags, f.Tag); err != nil {
			return err
		}
	}

	se.w.printf("if len(errs) > 0 {\n\treturn errs\n}\nreturn nil\n")
	se.w.indent(-1)
	se.w.printf("}\n")
	return nil
}

// emitField renders validation for one field (or dive element) value.
func (se *structEmitter) emitField(ref fieldRef, node *parser.TagNode, rawTag string) error {
	return se.emitValue(ref, node)
}

// emitValue dispatches to the nil handling for pointer/interface values and to
// the tag chain for everything else. validator unwraps pointers repeatedly.
func (se *structEmitter) emitValue(ref fieldRef, node *parser.TagNode) error {
	if ref.typ == nil {
		return nil
	}
	if ref.typ.Kind == parser.KindInterface {
		return se.emitInterface(ref, node)
	}
	if ref.typ.Kind == parser.KindPtr {
		return se.emitNullable(ref, node)
	}
	return se.emitChain(ref, node)
}

// interfacePresenceTags are the tags whose result for a non-nil interface is
// known without its dynamic type: they ask whether the interface is set at all.
var interfacePresenceTags = map[string]bool{
	"required":             true,
	"required_if":          true,
	"required_unless":      true,
	"required_with":        true,
	"required_with_all":    true,
	"required_without":     true,
	"required_without_all": true,
	"excluded_if":          true,
	"excluded_unless":      true,
	"excluded_with":        true,
	"excluded_with_all":    true,
	"excluded_without":     true,
	"excluded_without_all": true,
	"skip_unless":          true,
}

// emitInterface renders validation for an interface field. What an interface
// holds is only known at run time, so a static generator can evaluate the tags
// that depend on the interface being set (validator reads those through
// hasValue, i.e. a plain nil check) and nothing else: it reports the rest
// instead of emitting code that would quietly skip the check.
func (se *structEmitter) emitInterface(ref fieldRef, node *parser.TagNode) error {
	if node == nil {
		// validator returns immediately for an untagged interface: there is no
		// value to recurse into.
		return nil
	}
	if err := checkInterfaceTags(ref, node); err != nil {
		return err
	}

	// A non-nil interface is "set" whatever it holds, which is what hasValue
	// reports, so the interface stands in for its own unknown element.
	deref := ref
	deref.fromPointer = true

	skipWhenNil := false
	runWhenNil := false
	switch firstType(node) {
	case parser.TypeOmitEmpty, parser.TypeOmitNil, parser.TypeOmitZero, parser.TypeIsDefault:
		skipWhenNil = true
	default:
		runWhenNil = node.RunWhenNil
	}

	se.w.printf("if %s != nil {\n", ref.expr)
	se.w.indent(1)
	if err := se.emitChain(deref, node); err != nil {
		return err
	}
	se.w.indent(-1)

	if skipWhenNil {
		se.w.printf("}\n")
		return nil
	}

	se.w.printf("} else {\n")
	se.w.indent(1)
	if runWhenNil {
		nilRef := deref
		nilRef.knownNil = true
		if err := se.emitChain(nilRef, node); err != nil {
			return err
		}
	} else {
		// This branch knows the interface is nil, so its kind is the interface's
		// rather than the dynamic kind the non-nil branch reports.
		nilRef := ref
		nilRef.knownNil = true
		se.emitError(nilRef, node, firstAliasTag(node), firstParam(node))
	}
	se.w.indent(-1)
	se.w.printf("}\n")
	return nil
}

// checkInterfaceTags rejects tags that need the dynamic value of an interface.
func checkInterfaceTags(ref fieldRef, node *parser.TagNode) error {
	for n := node; n != nil; n = n.Next {
		switch n.Type {
		case parser.TypeOmitEmpty, parser.TypeOmitNil, parser.TypeOmitZero, parser.TypeIsDefault:
			continue
		case parser.TypeDefault:
			if interfacePresenceTags[n.Tag] {
				continue
			}
		}
		return fmt.Errorf("%s: %s cannot be validated on an interface field (%s): "+
			"what it holds is only known at run time, use a concrete type instead",
			ref.name, n.Tag, ref.typ.Expr)
	}
	return nil
}

// emitNullable mirrors validator's Ptr/Interface/Invalid pre-check.
func (se *structEmitter) emitNullable(ref fieldRef, node *parser.TagNode) error {
	elem := ref.typ.Elem
	if elem == nil {
		return nil
	}

	deref := ref
	deref.typ = elem
	deref.fromPointer = true
	deref.expr = "(*" + ref.expr + ")"
	if ref.typ.Kind == parser.KindInterface {
		// interface fields cannot be dereferenced statically; only nil checks apply.
		deref.expr = ref.expr
	}

	if node == nil {
		// Untagged field: validator only recurses into it.
		se.w.printf("if %s != nil {\n", ref.expr)
		se.w.indent(1)
		if err := se.emitValue(deref, nil); err != nil {
			return err
		}
		se.w.indent(-1)
		se.w.printf("}\n")
		return nil
	}

	skipWhenNil := false
	runWhenNil := false
	switch firstType(node) {
	case parser.TypeOmitEmpty, parser.TypeOmitNil, parser.TypeOmitZero, parser.TypeIsDefault:
		skipWhenNil = true
	default:
		if node != nil && node.RunWhenNil {
			runWhenNil = true
		}
	}

	se.w.printf("if %s != nil {\n", ref.expr)
	se.w.indent(1)
	if err := se.emitValue(deref, node); err != nil {
		return err
	}
	se.w.indent(-1)

	if skipWhenNil {
		se.w.printf("}\n")
		return nil
	}

	se.w.printf("} else {\n")
	se.w.indent(1)
	if runWhenNil {
		nilRef := deref
		nilRef.knownNil = true
		if err := se.emitValue(nilRef, node); err != nil {
			return err
		}
	} else {
		se.emitError(ref, node, firstAliasTag(node), firstParam(node))
	}
	se.w.indent(-1)
	se.w.printf("}\n")
	return nil
}

// emitChain walks a tag chain, mirroring validator's traverseField OUTER loop.
// The chain stops after the first failing check (validator returns there).
func (se *structEmitter) emitChain(ref fieldRef, node *parser.TagNode) error {
	// Structural prefixes (omitempty/omitzero/dive) are handled up front.
	switch firstType(node) {
	case parser.TypeOmitEmpty:
		se.w.printf("if %s {\n", se.hasValueExpr(ref))
		se.w.indent(1)
		if err := se.emitChain(ref, node.Next); err != nil {
			return err
		}
		se.w.indent(-1)
		se.w.printf("}\n")
		return nil

	case parser.TypeOmitZero:
		se.w.printf("if %s {\n", se.hasNotZeroValueExpr(ref))
		se.w.indent(1)
		if err := se.emitChain(ref, node.Next); err != nil {
			return err
		}
		se.w.indent(-1)
		se.w.printf("}\n")
		return nil

	case parser.TypeStructOnly, parser.TypeNoStructLevel:
		// validator returns here: neither the nested struct nor the remaining
		// tags are evaluated.
		return nil

	case parser.TypeOmitNil:
		// Only nilable kinds are skipped; everything else always validates.
		if t := ref.typ; t != nil && (t.Kind == parser.KindSlice || t.Kind == parser.KindMap ||
			t.Kind == parser.KindPtr || t.Kind == parser.KindInterface) {
			se.w.printf("if %s != nil {\n", ref.expr)
			se.w.indent(1)
			if err := se.emitChain(ref, node.Next); err != nil {
				return err
			}
			se.w.indent(-1)
			se.w.printf("}\n")
			return nil
		}
		return se.emitChain(ref, node.Next)

	case parser.TypeDive:
		return se.emitDive(ref, node)
	}

	if node == nil {
		return se.emitNested(ref)
	}

	// Boolean checks, chained so that later checks only run when earlier ones pass.
	expr, tail, report, err := se.nextCheck(ref, node)
	if err != nil {
		return err
	}
	if expr == "" {
		// Only structural work left.
		if err := se.emitChain(ref, tail); err != nil {
			return err
		}
		return se.emitNested(ref)
	}

	se.w.printf("if !(%s) {\n", expr)
	se.w.indent(1)
	se.emitError(ref, node, report, checkParam(node))
	se.w.indent(-1)

	// Everything after the last check is either the rest of the chain or the
	// automatic recursion into a nested struct - rendered up front so that an
	// empty tail does not leave a dangling else branch.
	rest, err := se.capture(func() error {
		if tail != nil {
			return se.emitChain(ref, tail)
		}
		return se.emitNested(ref)
	})
	if err != nil {
		return err
	}
	if rest != "" {
		se.w.printf("} else {\n")
		se.w.raw(rest)
	}
	se.w.printf("}\n")
	return nil
}

// capture renders code produced by fn without writing it to the output.
func (se *structEmitter) capture(fn func() error) (string, error) {
	var buf bytes.Buffer
	orig := se.w
	se.w = &codeWriter{buf: &buf, level: orig.level + 1}
	err := fn()
	se.w = orig
	return buf.String(), err
}

// nextCheck renders the boolean expression for the next check in the chain and
// returns the node that follows it.
func (se *structEmitter) nextCheck(ref fieldRef, node *parser.TagNode) (string, *parser.TagNode, string, error) {
	if node == nil {
		return "", nil, "", nil
	}

	switch node.Type {
	case parser.TypeStructOnly, parser.TypeNoStructLevel:
		return "", node.Next, "", nil

	case parser.TypeEndKeys:
		return "", nil, "", nil

	case parser.TypeOmitEmpty, parser.TypeOmitZero, parser.TypeOmitNil:
		return "", node.Next, "", nil
	}

	// An or-block: every consecutive TypeOr node is one alternative.
	if node.Type == parser.TypeOr || (node.Next != nil && node.Next.Type == parser.TypeOr) {
		expr, tail, err := se.emitOrBlock(ref, node)
		if err != nil {
			return "", nil, "", err
		}
		report := node.OrExpr()
		if node.HasAlias && node.AliasTag != "" {
			// validity came from an alias such as iscolor
			report = node.AliasTag
		}
		return expr, tail, report, nil
	}

	spec, ok := registry[node.Tag]
	if !ok {
		return "", nil, "", fmt.Errorf("unsupported validation tag %q", node.Tag)
	}
	expr, err := spec.emit(se, ref, node.Param)
	if err != nil {
		return "", nil, "", err
	}
	tail := node.Next
	if tail != nil && tail.Type == parser.TypeEndKeys {
		tail = nil
	}
	return expr, tail, checkTag(node), nil
}

// emitOrBlock renders `a|b|c`: valid when any alternative passes, reporting the
// whole expression when all fail (matching validator).
func (se *structEmitter) emitOrBlock(ref fieldRef, node *parser.TagNode) (string, *parser.TagNode, error) {
	var exprs []string
	cur := node
	var after *parser.TagNode
	for cur != nil && (cur.Type == parser.TypeOr || cur == node) {
		spec, ok := registry[cur.Tag]
		if !ok {
			return "", nil, fmt.Errorf("unsupported validation tag %q", cur.Tag)
		}
		expr, err := spec.emit(se, ref, cur.Param)
		if err != nil {
			return "", nil, err
		}
		exprs = append(exprs, expr)
		after = cur.Next
		if cur.IsBlockEnd {
			break
		}
		cur = cur.Next
	}
	return "(" + strings.Join(exprs, ") || (") + ")", after, nil
}

// emitDive renders iteration over a slice/array/map, applying the rest of the
// chain to each element (and, with keys/endkeys, to the map keys).
func (se *structEmitter) emitDive(ref fieldRef, node *parser.TagNode) error {
	typ := ref.typ
	valueNode := node.Next
	var keysNode *parser.TagNode
	if valueNode != nil && valueNode.Type == parser.TypeKeys {
		keysNode = valueNode.Keys
		valueNode = valueNode.Next
		if valueNode != nil && valueNode.Type == parser.TypeEndKeys {
			valueNode = valueNode.Next
		}
	}

	switch typ.Kind {
	case parser.KindSlice, parser.KindArray:
		if keysNode != nil {
			return fmt.Errorf("keys can only be used with maps")
		}
		se.g.addImport("strconv", "")
		se.diveDepth++
		idx := fmt.Sprintf("i%d", se.diveDepth)
		defer func() { se.diveDepth-- }()

		indexExpr := fmt.Sprintf("\"[\" + strconv.Itoa(%s) + \"]\"", idx)
		elem := fieldRef{
			expr:      fmt.Sprintf("%s[%s]", ref.expr, idx),
			typ:       typ.Elem,
			name:      ref.name + "[]",
			fieldExpr: fmt.Sprintf("%s + %s", ref.fieldExprOr(), indexExpr),
			ns:        fmt.Sprintf("%s + %s", ref.nsBase(), indexExpr),
			parent:    ref.parent,
		}
		body, err := se.capture(func() error { return se.emitElem(elem, valueNode) })
		if err != nil {
			return err
		}
		if strings.TrimSpace(body) == "" {
			return nil
		}
		se.w.printf("for %s := range %s {\n", idx, ref.expr)
		se.w.indent(1)
		se.w.raw(body)
		se.w.indent(-1)
		se.w.printf("}\n")

	case parser.KindMap:
		se.g.addImport("fmt", "")
		se.diveDepth++
		keyVar := fmt.Sprintf("k%d", se.diveDepth)
		valVar := fmt.Sprintf("v%d", se.diveDepth)
		defer func() { se.diveDepth-- }()

		indexExpr := fmt.Sprintf("\"[\" + fmt.Sprintf(\"%%v\", %s) + \"]\"", keyVar)
		base := fmt.Sprintf("%s + %s", ref.nsBase(), indexExpr)

		body, err := se.capture(func() error {
			if valueNode == nil {
				// only the keys are validated, the value stays unused
				se.w.printf("_ = %s\n", valVar)
			}
			if keysNode != nil {
				keyRef := fieldRef{
					expr:      keyVar,
					typ:       typ.Key,
					name:      ref.name + "[]",
					fieldExpr: fmt.Sprintf("%s + %s", ref.fieldExprOr(), indexExpr),
					ns:        base,
					parent:    ref.parent,
				}
				if err := se.emitElem(keyRef, keysNode); err != nil {
					return err
				}
			}
			if valueNode != nil {
				valRef := fieldRef{
					expr:      valVar,
					typ:       typ.Elem,
					name:      ref.name + "[]",
					fieldExpr: fmt.Sprintf("%s + %s", ref.fieldExprOr(), indexExpr),
					ns:        base,
					parent:    ref.parent,
				}
				return se.emitElem(valRef, valueNode)
			}
			return nil
		})
		if err != nil {
			return err
		}
		se.w.printf("for %s, %s := range %s {\n", keyVar, valVar, ref.expr)
		se.w.indent(1)
		se.w.raw(body)
		se.w.indent(-1)
		se.w.printf("}\n")

	default:
		return fmt.Errorf("dive requires a slice, array or map, got %s", typ.Expr)
	}
	return nil
}

// emitElem renders the chain for one dive element, dropping the block entirely
// when nothing is emitted for it.
func (se *structEmitter) emitElem(ref fieldRef, node *parser.TagNode) error {
	body, err := se.capture(func() error { return se.emitValue(ref, node) })
	if err != nil {
		return err
	}
	if strings.TrimSpace(body) == "" {
		return nil
	}
	se.w.printf("{\n")
	se.w.raw(body)
	se.w.printf("}\n")
	return nil
}

// emitNested recurses into a struct field, mirroring validator's automatic
// nested struct validation. time.Time is never recursed into.
func (se *structEmitter) emitNested(ref fieldRef) error {
	typ := ref.typ
	if typ == nil || typ.IsTime {
		return nil
	}
	if typ.Kind == parser.KindPtr && typ.Elem != nil {
		typ = typ.Elem
	}
	if typ.Kind != parser.KindStruct {
		return nil
	}
	if se.g.Pkg.StructByName(typ.Name) == nil {
		// Type declared elsewhere: validator would reflect over it, generated code cannot.
		return nil
	}
	se.w.printf("if err := %s.validate(%s); err != nil {\n", ref.expr, ref.nsBase())
	se.w.indent(1)
	se.w.printf("if verrs, ok := err.(%s.ValidationErrors); ok {\n", se.g.errPkg())
	se.w.printf("\terrs = append(errs, verrs...)\n")
	se.w.printf("} else if err != nil {\n\treturn err\n}\n")
	se.w.indent(-1)
	se.w.printf("}\n")
	return nil
}

// nsBase returns the Go expression for the namespace prefix of this field,
// i.e. what a nested value would prepend its own name to.
func (r fieldRef) nsBase() string { return r.ns }

// fieldExprOr falls back to the static name when no runtime expression is set.
func (r fieldRef) fieldExprOr() string {
	if r.fieldExpr != "" {
		return r.fieldExpr
	}
	return fmt.Sprintf("%q", r.name)
}

func (se *structEmitter) emitError(ref fieldRef, node *parser.TagNode, tag, param string) {
	if tag == "" {
		return
	}
	se.w.printf("errs = append(errs, %s.ValidationError{\n", se.g.errPkg())
	se.w.indent(1)
	fieldExpr := ref.fieldExpr
	if fieldExpr == "" {
		fieldExpr = fmt.Sprintf("%q", ref.name)
	}
	se.w.printf("Field: %s,\n", fieldExpr)
	se.w.printf("Tag: %q,\n", tag)
	if param != "" {
		se.w.printf("Param: %q,\n", param)
	}
	se.w.printf("Namespace: %s,\n", ref.ns)
	se.w.printf("StructNamespace: %s,\n", ref.ns)
	se.w.printf("ActualTag: %q,\n", actualTagOf(node, tag))
	switch {
	case ref.typ.Kind == parser.KindInterface && !ref.knownNil:
		// What an interface holds is only known at run time, and the reference
		// reports the kind of that value.
		qv := se.g.addImport(qvPath, "qv")
		se.w.printf("Kind: %s.DynamicKind(%s),\n", qv, ref.expr)
	default:
		if kind := reflectKind(ref.typ); kind != "" {
			se.g.addImport("reflect", "")
			se.w.printf("Kind: %s,\n", kind)
		}
	}
	if ref.knownNil {
		se.w.printf("Value: nil,\n")
	} else {
		se.w.printf("Value: %s,\n", ref.expr)
	}
	se.w.indent(-1)
	se.w.printf("})\n")
}

// actualTagOf renders the tag as it was written: an alias reports what it
// expands to ("iscolor" becomes "hexcolor|rgb|rgba|hsl|hsla"), a written
// or-branch reports the whole expression, a plain tag reports itself.
func actualTagOf(node *parser.TagNode, reported string) string {
	if node == nil {
		return reported
	}
	if node.ActualTag != "" {
		return node.ActualTag
	}
	if node.Type == parser.TypeOr {
		return node.OrExpr()
	}
	return node.Tag
}

// reflectKind renders the reflect.Kind the reference reports for a failure: the
// kind of the value at that point, which is the field's own kind once pointers
// have been unwrapped. The nil branch of a pointer keeps the pointer kind, and
// its errors are emitted with the pointer's own fieldRef.
func reflectKind(t *parser.TypeInfo) string {
	if t == nil {
		return ""
	}

	// The scalar kinds come from the underlying builtin: int and int64 share a
	// width but are different kinds to reflect, and a named int64 such as
	// time.Duration reports Int64.
	switch t.BuiltinName() {
	case "string":
		return "reflect.String"
	case "bool":
		return "reflect.Bool"
	case "int":
		return "reflect.Int"
	case "int8":
		return "reflect.Int8"
	case "int16":
		return "reflect.Int16"
	case "int32":
		return "reflect.Int32"
	case "int64":
		return "reflect.Int64"
	case "uint":
		return "reflect.Uint"
	case "uint8":
		return "reflect.Uint8"
	case "uint16":
		return "reflect.Uint16"
	case "uint32":
		return "reflect.Uint32"
	case "uint64":
		return "reflect.Uint64"
	case "uintptr":
		return "reflect.Uintptr"
	case "float32":
		return "reflect.Float32"
	case "float64":
		return "reflect.Float64"
	}

	switch t.Kind {
	case parser.KindSlice:
		return "reflect.Slice"
	case parser.KindArray:
		return "reflect.Array"
	case parser.KindMap:
		return "reflect.Map"
	case parser.KindPtr:
		return "reflect.Ptr"
	case parser.KindStruct:
		return "reflect.Struct"
	case parser.KindInterface:
		return "reflect.Interface"
	}
	return ""
}

func firstType(node *parser.TagNode) parser.TagType {
	if node == nil {
		return parser.TypeDefault
	}
	return node.Type
}

func firstAliasTag(node *parser.TagNode) string {
	if node == nil {
		return ""
	}
	if node.AliasTag != "" {
		return node.AliasTag
	}
	return node.Tag
}

func firstParam(node *parser.TagNode) string { return checkParam(node) }

// checkTag is the tag reported when the check at node fails.
func checkTag(node *parser.TagNode) string {
	if node == nil {
		return ""
	}
	if node.AliasTag != "" {
		return node.AliasTag
	}
	return node.Tag
}

func checkParam(node *parser.TagNode) string {
	if node == nil {
		return ""
	}
	return node.Param
}

// codeWriter is a tiny indenting writer.
type codeWriter struct {
	buf   *bytes.Buffer
	level int
}

func newWriter(buf *bytes.Buffer) *codeWriter { return &codeWriter{buf: buf} }

func (w *codeWriter) indent(delta int) { w.level += delta }

// raw appends already rendered (and already indented) code.
func (w *codeWriter) raw(code string) { w.buf.WriteString(code) }

func (w *codeWriter) printf(format string, args ...interface{}) {
	if w.level > 0 {
		w.buf.WriteString(strings.Repeat("\t", w.level))
	}
	fmt.Fprintf(w.buf, format, args...)
	if !strings.HasSuffix(format, "\n") {
		w.buf.WriteString("\n")
	}
}

// otherRef resolves a (possibly dotted) sibling field path to a Go expression.
// Paths that traverse a pointer are rejected: validator resolves them at run
// time and reports "not found" for nil pointers.
// otherRef resolves a cross field path such as "A.B" into an expression and its
// type. guard is a Go expression that is true when every pointer on the way is
// non-nil; the reference reports a path through a nil pointer as "not found",
// which each caller turns into a pass or a failure of its own.
func (se *structEmitter) otherRef(path string) (expr string, typ *parser.TypeInfo, guard string, ok bool) {
	// validator's *csfield tags take a namespace such as "User.Country"; strip
	// the leading struct name when it names the current struct.
	if i := strings.Index(path, "."); i > 0 && path[:i] == se.name {
		path = path[i+1:]
	}
	parts := strings.Split(path, ".")
	expr = "s"
	var guards []string
	var cur *parser.TypeInfo

	for i, part := range parts {
		var f *parser.FieldInfo
		if i == 0 {
			f = se.fields[part]
		} else {
			if cur == nil || cur.Kind != parser.KindStruct {
				return "", nil, "", false
			}
			st := se.g.Pkg.StructByName(cur.Name)
			if st == nil {
				return "", nil, "", false
			}
			for j := range st.Fields {
				if st.Fields[j].Name == part {
					f = &st.Fields[j]
					break
				}
			}
		}
		if f == nil {
			return "", nil, "", false
		}

		expr += "." + part
		cur = f.Type

		if cur.Kind == parser.KindPtr {
			if cur.Elem == nil {
				return "", nil, "", false
			}
			guards = append(guards, expr+" != nil")
			if i == len(parts)-1 {
				// The comparison reads what the pointer points at.
				expr = "(*" + expr + ")"
			}
			cur = cur.Elem
		}
	}
	return expr, cur, strings.Join(guards, " && "), true
}

// notFoundResult is what the reference returns when the other field cannot be
// resolved: the negative comparisons treat that as a pass, the positive ones as
// a failure.
func notFoundResult(op string) string {
	if op == "!=" {
		return "true"
	}
	return "false"
}

// withGuard renders "guard ? check : notFound", collapsing to the plain check
// when there is no pointer to guard and not-found means failure.
func withGuard(check, guard string, notFoundPasses bool) string {
	if guard == "" {
		return check
	}
	if notFoundPasses {
		return fmt.Sprintf("!(%s) || (%s)", guard, check)
	}
	return fmt.Sprintf("(%s) && (%s)", guard, check)
}
